### ISSUE TITLE
How to retrieve player data?

### ISSUE THREAD

**Issue by DylanDelobel** [claabs/csgostatsgg-scraper#10]
Here my snippet

I tried true/false (npm install local hero)
```ts
export const csgo = new CSGOStatsGGScraper({
    useLocalHero: true
});
```
with
```ts
const data = await csgo.getPlayer('76561197983832927');
console.log(data);
 ```
I got the following output
```ts
2023-08-03T13:16:22.738Z ERROR [hero-core\connections\ConnectionToHeroClient] ConnectionToClient.HandleRequestError {
  context: {},
  sessionId: '8dhUWdGGicT3Trw2amTRI',
  sessionName: undefined
} InjectedScriptError: TypeError: Cannot read properties of null (reading 'src')
    at JsPath.runJsPath (DiscordBotBot\agent\main\lib\JsPath.ts:165:13)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at process.processImmediate (node:internal/timers:447:9)
    at async FrameEnvironment.execJsPath (DiscordBotBot\node_modules\core\lib\FrameEnvironment.ts:245:12)
    at async CommandRecorder.runCommandFn (DiscordBotBot\node_modules\core\lib\CommandRecorder.ts:90:16)
    at async CommandRunner.runFn (DiscordBotBot\node_modules\core\lib\CommandRunner.ts:36:14)
    at async ConnectionToHeroClient.executeCommand (DiscordBotBot\node_modules\core\connections\ConnectionToHeroClient.ts:258:12)
    at async ConnectionToHeroClient.handleRequest (DiscordBotBot\node_modules\core\connections\ConnectionToHeroClient.ts:66:14) {
  pathState: { step: 'src', index: 2 }
}
InjectedScriptError: TypeError: Cannot read properties of null (reading 'src')
    at JsPath.runJsPath (DiscordBotBot\agent\main\lib\JsPath.ts:165:13)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at process.processImmediate (node:internal/timers:447:9)
    at async FrameEnvironment.execJsPath (DiscordBotBot\node_modules\core\lib\FrameEnvironment.ts:245:12)
    at async CommandRecorder.runCommandFn (DiscordBotBot\node_modules\core\lib\CommandRecorder.ts:90:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async AwaitedHandler.getProperty (DiscordBotBot\node_modules\files\2-finalized\awaited-dom\base\AwaitedHandler.ts:25:12)
    at async CSGOStatsGGScraper.getPlayer (DiscordBotBot\node_modules\csgostatsgg-scraper\src\player.ts:174:29)
    at async run (DiscordBotBot\node_modules\p-queue\dist\index.js:163:29)

--------------------------------------------------
--------------------------------------------------
------8dhUWdGGicT3Trw2amTRI-----------------------
-------------------------------------------------- {
  pathState: { step: 'src', index: 2 }
}
```
I don't understand what the error here is to debug further

**Comment by sruusk** [comment]
It fails to get the esea url. The csgostats developer likes to use esea company time to keep breaking this package.

**Comment by DylanDelobel** [comment]
@sruusk Is there a older version I could rollback or a quickfix to skip esea results ? 🙏

**Comment by sruusk** [comment]
I only collects the link to the esea profile. Should probably just remove it from the scraper entirely. What do you think @claabs?

**Comment by sruusk** [comment]
Oh, and there is no way to rollback or skip the esea link at the moment.

**Comment by DylanDelobel** [comment]
Any update?

**Comment by claabs** [comment]
I'm not able to actively maintain this package anymore. Feel free to make a PR with the needed fixes.
